### ISSUE TITLE
Bug with keyboard shortcuts

### ISSUE THREAD

**Issue by piereligio** [XQS6LB3A/TouchDock#2]
I selected command key as shortcut, but even when I click either option or control, or shift key, it will hide touchdock, like if they were the ones assigned.

**Comment by ddddxxx** [comment]
Yes, currently I just check the status of the key whenever a key is pressed/released, and show/hide touchdock correspondingly. The behavior is confusing.

I’ll fix this soon.

**Comment by piereligio** [comment]
Nice, thank you :)
