### ISSUE TITLE
Another way for scrolling?

### ISSUE THREAD

**Issue by piereligio** [XQS6LB3A/TouchDock#4]
I don't know if I am asking too much, but I would like to be able to scroll the apps icons like the scrolling of any collection view.
Currently it scrolls when you are holding touch while the finger is over the borders of the list, I would like to see it scrolling like any app on a phone, to be clear. 
Obviously as an option, since current modality lets you to scroll and select the app in a single gesture, which may be cool for some people.

**Comment by ddddxxx** [comment]
Not at all. You are helping to improve this app :)

It will be done in the next release.

**Comment by ddddxxx** [comment]
update to 0.1.3 and enjoy :)

// Sorry, I just found that I forgot to release 0.1.2, did you build on your own?

**Comment by piereligio** [comment]
Uh no, I think you did release 0.1.2 o.o
I'll try the update asap

**Comment by piereligio** [comment]
Great, this feature works perfect
