### ISSUE TITLE
Randomly quits

### ISSUE THREAD

**Issue by ghost** [XQS6LB3A/TouchDock#8]
I noticed that TouchDock randomly quits. I put it in my startup objects, and after some time I notice that the icon on the right side of the Touch Bar disappears. The app is gone in the Activity Monitor, but if I restart the app it works again for some time.

2018 MacBook Pro with macOS 10.13.6

Also have the issue listed here: https://github.com/ddddxxx/TouchDock/issues/6

**Comment by ddddxxx** [comment]
It seems the app crashed. You can find the report from `Console.app` -> User Diagnostic Reports. Please attach the report here.

**Comment by ghost** [comment]
There is no crash report, seems like the app quit normally. Maybe I closed it by accident.
