### ISSUE TITLE
Breaks on Mojave

### ISSUE THREAD

**Issue by dfdy** [XQS6LB3A/TouchDock#9]
Unfortunately this really great little tool does not load successfully on macOS Mojave. 

After starting the app it shows its icon in the default set, but the hotkey does not work, nor does tapping the icon. The process is in memory and needs to be shut down via System Monitor.

**Comment by ddddxxx** [comment]
Thanks for your report. The app uses private API to show icon on system control stripe. It seems Apple changed behavior of these API. I'll look into it.

**Comment by ddddxxx** [comment]
Fixed: https://github.com/ddddxxx/TouchDock/releases/tag/v0.2.0
